[theme]
base = "light"
primaryColor = "#A8762E"
backgroundColor = "#F2EEE6"
secondaryBackgroundColor = "#E9E2D2"
textColor = "#141414"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableStaticServing = true

[browser]
gatherUsageStats = false
